// Code generated by {{.BinName}}.
//
// Copyright {{.BinYear}} {{.BinAuth}} Technologies Ltd. All rights reserved.
//
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file in the root of the source
// tree.

package {{.PktName}}

type (
    {{.TypName}}  struct{
    ...
    }
    Option         interface{
    ...
    }
)